import { useEffect,useState } from 'react'
import { useAuth } from '../App'
import { listGroups } from '../services/groupService'
import { listHomework,createHomework,updateHomework } from '../services/homeworkService'
import Modal from '../components/Modal'; import Loading from '../components/Loading'; import ErrorState from '../components/ErrorState'
const blank={group_id:'',title:'',description:'',due_date:new Date().toISOString().slice(0,10),max_score:100}
export default function Homework(){const {profile}=useAuth();const isAdmin=profile?.role==='admin';const [groups,setGroups]=useState([]),[items,setItems]=useState([]),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[error,setError]=useState('')
async function load(){try{setLoading(true);setError('');const gs=await listGroups();setGroups(gs);setItems(await listHomework(gs.map(g=>g.id)))}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[profile?.id])
function startCreate(){setEditing(null);setForm({...blank,group_id:groups[0]?.id?String(groups[0].id):''});setOpen(true)}
function startEdit(x){setEditing(x);setForm({group_id:String(x.group_id),title:x.title,description:x.description||'',due_date:x.due_date||'',max_score:x.max_score});setOpen(true)}
async function submit(e){e.preventDefault();try{const group=groups.find(g=>String(g.id)===String(form.group_id));if(!group?.instructor_id)throw new Error('The selected group has no instructor. Assign one to the group first.');const payload={...form,group_id:Number(form.group_id),instructor_id:group.instructor_id,max_score:Number(form.max_score)};if(editing)await updateHomework(editing.id,payload);else await createHomework(payload);setOpen(false);await load()}catch(e){setError(e.message)}}
if(loading)return <Loading/>;if(error&&!open)return <ErrorState message={error} onRetry={load}/>;return <div><div className="page-heading"><div><h1>Homework</h1><p>{isAdmin?'View and edit every homework task.':'Create and edit homework for your groups.'}</p></div><button className="btn" onClick={startCreate}>+ New homework</button></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Group</th><th>Instructor</th><th>Title</th><th>Due date</th><th>Max score</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.groups?.name}</td><td>{x.profiles?.full_name||'—'}</td><td>{x.title}</td><td>{x.due_date||'—'}</td><td>{x.max_score}</td><td><button className="text-btn" onClick={()=>startEdit(x)}>Edit</button></td></tr>)}</tbody></table></div></div>{open&&<Modal title={editing?'Edit homework':'Create homework'} onClose={()=>setOpen(false)}><form onSubmit={submit} className="form-grid"><label>Group<select value={form.group_id} onChange={e=>setForm({...form,group_id:e.target.value})} required><option value="">Select group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name} — {g.profiles?.full_name||'No instructor'}</option>)}</select></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Due date<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label>Max score<input type="number" min="1" value={form.max_score} onChange={e=>setForm({...form,max_score:e.target.value})}/></label><label className="full">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn">{editing?'Save changes':'Create'}</button></div></form></Modal>}</div>}
