import { useEffect, useState } from 'react'
import { useAuth } from '../App'
import { listGroups } from '../services/groupService'
import { listStudents, createStudent, updateStudent } from '../services/studentService'
import Modal from '../components/Modal'; import Loading from '../components/Loading'; import ErrorState from '../components/ErrorState'

const blank = { full_name: '', phone: '', parent_phone: '', group_id: '', status: 'active', join_date: '' }

export default function Students() {
  const { profile } = useAuth(); const [groups, setGroups] = useState([]), [students, setStudents] = useState([])
  const [groupId, setGroupId] = useState('all'), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(blank)
  async function load() { try { setLoading(true); setError(''); const gs = await listGroups(); setGroups(gs); setStudents(await listStudents(gs.map(g => g.id))) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [profile?.id])
  function startCreate() { setEditing(null); setForm({ ...blank, group_id: groups[0]?.id ? String(groups[0].id) : '' }); setOpen(true) }
  function startEdit(s) { setEditing(s); setForm({ full_name: s.full_name, phone: s.phone || '', parent_phone: s.parent_phone || '', group_id: s.group_id ? String(s.group_id) : '', status: s.status, join_date: s.join_date || '' }); setOpen(true) }
  async function submit(e) { e.preventDefault(); if (!editing && profile?.role !== 'admin') { setError('Only administrators can add students.'); return } try { const payload = { ...form, group_id: form.group_id ? Number(form.group_id) : null, join_date: form.join_date || undefined }; if (editing) await updateStudent(editing.id, payload); else await createStudent(payload); setOpen(false); await load() } catch (e) { setError(e.message) } }
  if (loading) return <Loading />; if (error && !open) return <ErrorState message={error} onRetry={load} />
  const visible = groupId === 'all' ? students : students.filter(s => String(s.group_id) === groupId)
  return <div><div className="page-heading"><div><h1>Students</h1><p>{profile?.role === 'admin' ? 'View and edit every student.' : 'View and edit students in your groups.'}</p></div>{profile?.role === 'admin' && <button className="btn" onClick={startCreate}>+ New student</button>}</div><div className="toolbar"><select value={groupId} onChange={e => setGroupId(e.target.value)}><option value="all">All groups</option>{groups.map(g => <option value={g.id} key={g.id}>{g.name}</option>)}</select></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Student</th><th>Group</th><th>Phone</th><th>Parent phone</th><th>Status</th><th>Join date</th><th></th></tr></thead><tbody>{visible.map(s => <tr key={s.id}><td>{s.full_name}</td><td>{s.groups?.name || '—'}</td><td>{s.phone || '—'}</td><td>{s.parent_phone || '—'}</td><td><span className={`badge ${s.status}`}>{s.status}</span></td><td>{s.join_date || '—'}</td><td><button className="text-btn" onClick={() => startEdit(s)}>Edit</button></td></tr>)}</tbody></table></div></div>{open && <Modal title={editing ? 'Edit student' : 'Add student'} onClose={() => setOpen(false)}><form onSubmit={submit} className="form-grid"><label>Full name<input value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} required /></label><label>Student phone<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label>Parent phone<input value={form.parent_phone} onChange={e => setForm({ ...form, parent_phone: e.target.value })} /></label><label>Group<select value={form.group_id} onChange={e => setForm({ ...form, group_id: e.target.value })} required><option value="">Select group</option>{groups.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="active">Active</option><option value="paused">Paused</option><option value="inactive">Inactive</option></select></label><label>Join date<input type="date" value={form.join_date} onChange={e => setForm({ ...form, join_date: e.target.value })} /></label><div className="form-actions"><button className="btn secondary" type="button" onClick={() => setOpen(false)}>Cancel</button><button className="btn">{editing ? 'Save changes' : 'Add'}</button></div></form></Modal>}</div>
}
